### ISSUE TITLE
Support UNICORN 7 Result Files

### ISSUE THREAD

**Issue by kvr2007** [pyahmed/PyCORN#13]
*.res files supported by the script are generated by UNICORN 5, however, starting from UNICORN 7 the native format for result export is a *.zip archive with some *.xml files and data containers. Would it be possible to support these, too? I would be happy to provide a sample file :)

**Comment by pyahmed** [comment]
I added support for the zip archives in v0.17 - try to update to that version. It should just work. I had only zip files from UNICORN 6 to test. If files from v7 are much different - then yes samples will be helpful :-)

**Comment by kvr2007** [comment]
Cool, thanks for the information! I'll check the newest version with my data and report back.

**Comment by pyahmed** [comment]
Yeah.. support for zip-bundles is a bit of a hack. One day I might get around to fix the remaining things - until then, closed :-)
